export const SHOW_NAV = "SHOW_NAV";
export const HIDE_NAV = "HIDE_NAV";

export const SHOW_MARKER_DETAILS = "SHOW_MARKER_DETAILS";
export const HIDE_MARKER_DETAILS = "HIDE_MARKER_DETAILS";

export const GET_MOVIE_DETAILS_REQUEST = "GET_MOVIE_DETAILS_REQUEST";
export const GET_MOVIE_DETAILS_SUCCESS = "GET_MOVIE_DETAILS_SUCCESS";
export const GET_MOVIE_DETAILS_ERROR = "GET_MOVIE_DETAILS_ERROR";

export const SET_RADIUS = "SET_RADIUS";

export const SET_CURRENT_LOCATION = "SET_CURRENT_LOCATION";
