export const SHOW_NAV = "SHOW_NAV";
export const HIDE_NAV = "HIDE_NAV";

export const SHOW_MARKER_DETAILS = "SHOW_MARKER_DETAILS";
export const HIDE_MARKER_DETAILS = "HIDE_MARKER_DETAILS";
export const SHOW_IMAGES = "SHOW_IMAGES";
export const HIDE_IMAGES = "HIDE_IMAGES";

export const GET_MOVIE_DETAILS_REQUEST = "GET_MOVIE_DETAILS_REQUEST";
export const GET_MOVIE_DETAILS_SUCCESS = "GET_MOVIE_DETAILS_SUCCESS";
export const GET_MOVIE_DETAILS_ERROR = "GET_MOVIE_DETAILS_ERROR";

export const SET_RADIUS = "SET_RADIUS";

export const SET_CURRENT_LOCATION = "SET_CURRENT_LOCATION";

export const GET_NEARBY_IMAGES_REQUEST = "GET_NEARBY_IMAGES_REQUEST";
export const GET_NEARBY_IMAGES_SUCCESS = "GET_NEARBY_IMAGES_SUCCESS";
export const GET_NEARBY_IMAGES_ERROR = "GET_NEARBY_IMAGES_ERROR";

export const SET_DIRECTIONS = "SET_DIRECTIONS";
export const RESET_DIRECTIONS = "RESET_DIRECTIONS";
